version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: clase-next-db
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: clase-next-db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
