version: "3.8"
services:
  db:
    container_name: "clase-next-db"
    image: mysql
    restart: always
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - clase-next-db:/var/lib/mysql/data

volumes:
  clase-next-db:
    name: clase-next-db
    driver: local
